### ISSUE TITLE
ImportError: DLL load failed Windows bat install

### ISSUE THREAD

**Issue by UserB-tm** [ParisNeo/gpt4all-ui#202]
## Expected Behavior
Run the follow in PowerShell on new Windows computer
git clone https://github.com/nomic-ai/gpt4all-ui.git
and gpt4all-ui is installed on new Windows computer.

## Current Behavior
After cloning repostitory cmd freezes an returns the following Traceback:
Traceback (most recent call last):
  File "C:\Users\ATS\Documents\NewInstance\gpt4all-ui\app.py", line 39, in <module>
    from geventwebsocket.handler import WebSocketHandler
  File "C:\Users\ATS\Documents\NewInstance\gpt4all-ui\env\lib\site-packages\geventwebsocket\handler.py", line 4, in <module>
    from gevent.pywsgi import WSGIHandler
  File "C:\Users\ATS\Documents\NewInstance\gpt4all-ui\env\lib\site-packages\gevent\__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "C:\Users\ATS\Documents\NewInstance\gpt4all-ui\env\lib\site-packages\gevent\_hub_local.py", line 101, in <module>    import_c_accel(globals(), 'gevent.__hub_local')
  File "C:\Users\ATS\Documents\NewInstance\gpt4all-ui\env\lib\site-packages\gevent\_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "C:\Users\ATS\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src\\gevent\\_hub_local.py", line 1, in init gevent._gevent_c_hub_local
  File "C:\Users\ATS\Documents\NewInstance\gpt4all-ui\env\lib\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: DLL load failed while importing _greenlet: The specified module could not be found.

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. Verified prerequisites were installed, i.e., python 3.10 "not from MS store, but official site", git. 
2. Opened PowerShell in folder/s and ran clone script.
3. I have tried several fixes, such as pip installing all requirement individually, uninstalling and reinstalling python, attempted install in multiple directories, uninstalling reinstalling and updating greenlet, updating Windows, checking for possible blockage by Windows security, several turns with ChatGpt, and ran suggestions. 

## Possible Solution
No idea at this point

## Context
Testing install on new dell latitude 5420, i7 11g 3.0ghz, 16gb ram, 500gb ssd, Intel
<img width="466" alt="cmdGpt4all-UIDllError" src="https://github.com/nomic-ai/gpt4all-ui/assets/130169859/fc57051e-e2d3-4ef0-90da-e5680318e2d0">
<img width="665" alt="pipList" src="https://github.com/nomic-ai/gpt4all-ui/assets/130169859/4a016beb-7e7c-441c-a84a-15fee0289ae9">
 Iris Xe Graphics, Windows 10 22h2

## Screenshots
If applicable, add screenshots to help explain the issue.

**Comment by ParisNeo** [comment]
try run the webui.bat from cmd, it should do all necessary installations.

**Comment by UserB-tm** [comment]
Still hitting a wall. Not sure why. 
<img width="674" alt="webuiBat1" src="https://github.com/nomic-ai/gpt4all-ui/assets/130169859/d53fe7c7-2b63-4eab-bc35-cc2f0d68a841">
<img width="674" alt="webuiBat2" src="https://github.com/nomic-ai/gpt4all-ui/assets/130169859/136bba69-32cf-4a99-a4bc-a8bed112ea68">

**Comment by UserB-tm** [comment]
I just noticed that since I created another NT account on this computer, the new account isn't recognizing that Python is installed, so I'll pull it in.

**Comment by jonopryor** [comment]
If you are using Windows Server try installing the VC redstributable - 

https://download.visualstudio.microsoft.com/download/pr/eaab1f82-787d-4fd7-8c73-f782341a0c63/917C37D816488545B70AFFD77D6E486E4DD27E2ECE63F6BBAAF486B178B2B888/VC_redist.x64.exe
