### ISSUE TITLE
Discussions are not saved

### ISSUE THREAD

**Issue by okkebal** [ParisNeo/gpt4all-ui#218]
## Expected Behavior
I expect the discissions (Chats) to be saved.

## Current Behavior
Discussions are not saved. When generation ends this is not detected bij the UI. It keeps saying  "Stop Generating". Since the end of generation is not detected the message is never saved.

## Steps to Reproduce
1: Install WebUI: 

2: I am not running it on localhost but on 192.168.178.73. In order to do that I edit /config/local_default.yaml host entry. 

3. I change the first line in /web/.env and then run "npm install" and "npm run build" in the /web folder. If I don't do that last part with npm I get Cross site scripting errors when trying to send questions to the server.

## Possible Solution
I think the string something like: '#### end generation ####' that was added previousely in the output of the model is no longer produced so the system does not know when generation is done.

## Context
Not running on /localhost but on LAN adress.

## Screenshots
If applicable, add screenshots to help explain the issue.

**Comment by Nyandaro** [comment]
It may not be relevant to this topic, but just in case

I get this error even in old UI
When I change config to Old UI and start
Failed to query the discussion
After that, if you enter HELLO, the following error message will appear


Please open your browser and go to http://localhost:9600 to view the ui
debug mode:true
 ******************* Building Backend from generation Process *************************
Loading backend llama_cpp_official install ON
Backend loaded successfully
Loading model : models\llama_cpp_official\ggml-mpt-7b-chat.bin
llama.cpp: loading model from ./models/llama_cpp_official/ggml-mpt-7b-chat.bin
error loading model: unknown (magic, version) combination: 67676d6d, 0000c500; is this really a GGML file?
llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "C:\z\GPT4All\gpt4all_api\api.py", line 194, in _rebuild_model
    self.model = self.backend(self.config)
  File "C:\z\GPT4All\backends\llama_cpp_official\__init__.py", line 43, in __init__
    self.model = Llama(model_path=f"./models/llama_cpp_official/{self.config['model']}", n_ctx=self.config["ctx_size"], n_gpu_layers=self.config["n_gpu_layers"], seed=seed)
  File "C:\z\GPT4All\env\lib\site-packages\llama_cpp\llama.py", line 162, in __init__
    assert self.ctx is not None
AssertionError
Couldn't build model

 ******************* Building Personality gpt4all from generation Process *************************
 ************ Personality gpt4all is ready (generation process) ***************************
No model loaded. Waiting for new configuration instructions
Listening on :http://localhost:9600
Client connected
- Loading discussion
    Recovered json data
ERROR:GPT4All-WebUI:Exception on /load_discussion [POST]
Traceback (most recent call last):
  File "C:\z\GPT4All\env\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\z\GPT4All\env\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\z\GPT4All\env\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\z\GPT4All\env\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\z\GPT4All\app.py", line 611, in load_discussion
    print(f"    Discussion id :{discussion_id}")
UnboundLocalError: local variable 'discussion_id' referenced before assignment



and the following tab will appear
"It seems that no model has been loaded. Please download and install a model first, then try again."



This error does not appear in the NEW UI

**Comment by DifferentialityDevelopment** [comment]
Think you're supposed to put MPT models in the models/c_transformers folder?
I say this because I notice you're running ggml-mpt-7b-chat.bin which is an MPT model and you've put it in llama_cpp_official
Anyways unless llamacpp natively supports MPT models now too? Lot of the latest TheBloke repo's on hugging face specifically mention it doesn't work on llama.cpp.
Anyways hope that's helpful

**Comment by okkebal** [comment]
Did some more research. It depends on the model. The ones that give problems for me in py_llama_cpp backend are ggml-vic13b-uncensored-q4_0.bin and medalpaca-13B.ggmlv2.q4_0.bin

**Comment by Nyandaro** [comment]
Wonderful, you saw through that I was an amateur.

I didn't think too much about which MODEL is related to which folder.
The reason is that it worked even if I put all the various MODELs into llama_cpp_official.
I thought it was structured so that it could be read regardless of which folder it was placed in.

I tried putting it in c_transformers, but the behavior doesn't change.

In my case, TheBloke only works with GGML V2 type.

**Comment by ParisNeo** [comment]
Hi guys. The problem with this is that. Ackends change and they change fast and break compatibility. That's why i end up having the models zoo broken.
Need someone to help me maintain the zoo.

**Comment by okkebal** [comment]
> Hi guys. The problem with this is that. backends change and they change fast and break compatibility. That's why i end up having the models zoo broken. Need someone to help me maintain the zoo.

This is the models I've tested so far: https://github.com/ParisNeo/gpt4all-ui/pull/222

**Comment by okkebal** [comment]
It would help if it saved discussions on cancel generation, or even after each word. I can't figure out in the code how this database works or where or when it even saves stuff.

**Comment by ParisNeo** [comment]
Hi. I have seen this problem last night. I'll fix it. And yes, good idea about saving when you press ca'cel

**Comment by andzejsp** [comment]
> It would help if it saved discussions on cancel generation, or even after each word. I can't figure out in the code how this database works or where or when it even saves stuff.

not sure what you are describing, but discussion is saved once you get a response or once discussion is created.

Maybe something else broke down while you were typing your message, good to open up web browser > inspect > console  and also check the webui.bat/sh conoler for any errors.

Would be even better if you could record your errors on video or something.. pictures..

**Comment by okkebal** [comment]
If a discussion is generating. Open a different browser and go to that discussion. It will remain empty until generation is done. Only then is the discussion saved and available in the other browser. The generating discussion is only viewable from the browser it has been started in until it is completely done generating. Only then is it saved. Sometimes a model does not signal is stopped generating. Alhough CPU usage drops and the answer is clearly done, the model does not signal it stopped, so the discussion is never saved. I must say that the last couple of days I do not have this problem anymore and the models all seem te signal that they stopped generating.
