### ISSUE TITLE
./setup.sh does not install all the prerequisets

### ISSUE THREAD

**Issue by rempel1234** [ParisNeo/gpt4all-ui#256]
## Expected Behavior
Running ./setup.sh install all required python modules

## Current Behavior
Loading binding c_transformers install ON
Traceback (most recent call last):
  File "/home/gpt4all/gpt4all-ui/api/__init__.py", line 218, in _rebuild_model
    self.binding = self.load_binding(self.config["binding"], install=True)
  File "/home/gpt4all/gpt4all-ui/api/__init__.py", line 158, in load_binding
    binding_module = loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gpt4all/gpt4all-ui/bindings/c_transformers/__init__.py", line 18, in <module>
    from ctransformers import AutoModelForCausalLM
ModuleNotFoundError: No module named 'ctransformers'
Couldn't build binding

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. Log into Debian Windows Subsystem for Linux with python3.10 and python3.11 installed
2. Run ./setup.sh
3. Browse to 127.0.0.1:9600
4. Click on Settings
5. Expand Bindings zoo
6. Click on C Transformers
7. Attempt a conversation

## Possible Solution
Add an exception handler to install the missing python modules "/home/gpt4all/gpt4all-ui/api/__init__.py" for line 158 load_binding, if the module is missing or perhaps add the missing modules to requirements.txt

## Context
Debian VM with both python3.10 and 3.11

**Comment by ParisNeo** [comment]
go to the bindings folder, then to c_transformers and remove .installed then re-run. It should install all required things for that binding. the setup installs a minimal configuration then when you first run a binding it installs its requirements. And I think someone forgot to remove .installed from the git before committing and that's why it si not working for you. This file indicates that the binding is already installed.

I'm not reparing this as I am working on a new branch that has already fixed this issue. It will be merged soon.

**Comment by CSnowRules** [comment]
I've found for deb/Ubuntu, build-essential isn't a prerequisite. It should be as it isn't installed by default on (many) installations.
That is--if you haven't already fixed this. I appreciate your contribution.

**Comment by ParisNeo** [comment]
Hi. I'm preparing a new video on the new conda based installation. It installs everything you need with cuda and build tools.
I didn't yet test the linux version. Coded it blindly since i have no linux machines this time around.
